services:
  - type: web
    name: database-essentials-api
    runtime: docker
    repo: https://github.com/Null-Nil-None/database_essentials
    branch: main
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: default
